import {Cinzel } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header"
import Footer from "@/components/Footer";

// const inter = Inter({ subsets: ["latin"] });
const cinzelfont = Cinzel({
  subsets:['latin'],
  weight:['400','500','600','700','800','900'],
  variable:'--font-cazel'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cinzelfont.variable}>
        {children}
        </body>
    </html>
  );
}
